reastaurant_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('  /', include('manager.urls')),
    path('rest_admin/', include('rest_admin.urls')),
    path('waiter/', include('waiter.urls')),
    path('kitchen/', include('kitchen.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('webpush/', include('webpush.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'restaurant'

urlpatterns = [
    path('', views.index, name='index'),
    path('menu/<int:id>/<int:pk>/', views.menu_list, name='menu'),
    path('add_to_cart/<int:id>/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:id>/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove_s_from_cart/<int:id>/<int:pk>/', views.remove_single_item_from_cart, name='remove_single'),
    path('order_summary/<int:id>/<int:id2>/', views.order_summary, name='order_summary'),
    path('place_order/<int:id>/<int:id2>/', views.proceed_to_pay, name='place_order'),
    path('call_waiter/<int:id>/', views.call_a_waiter, name='call_waiter'),
    path('com/<int:id>/', views.comment, name='com'),
    path('add_to_cart_order/<int:id>/<int:pk>/', views.add_to_cart_order, name='add_to_cart_order'),
    path('remove_from_cart_order/<int:id>/<int:pk>/', views.remove_single_item_from_cart_order, name='remove_from_cart_order'),

] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

waiter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'waiter'

urlpatterns = [
    path('', views.table_view, name='table_view'),
    path('manual_order/<int:id>/', views.manual_order, name='manual_order'),
    path('t_orders/', views.today_order, name='t_order'),
] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/customer copy/menu.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />

    <link rel="stylesheet" href="{% static 'menu_page/w3.css' %}" />
    <link rel="stylesheet" href="{% static 'menu_page/bootstrap.min.css' %}" />
    <link
      rel="stylesheet"
      href="{% static 'menu_page/font-awesome.min.css' %}"
    />
    <link
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'my_css/menu.css' %}"
    />

    <title>Scan N Order</title>
  </head>
  <body style="margin-left: 18px; margin-right: 10px">
    <!-- navigation Start Here -->
    <div class="topnav" style="background-color: #abe63a" id="myTopnav">
      <a href="#home" class="text-white"
        >{{ table.rest.restaurant_name|capfirst }}</a
      >
    </div>
    <!-- end here -->

    <!--search form here -->
    <div class="container-fluid bg-light p-2">
      <form class="form-group row col-md-12">
        <input
          type="email"
          class="form-control col-md-10 col-10"
          placeholder="Dish Name"
          id="inputEmail4"
        />
        <button
          type="submit"
          class="form-control col-md-2 col-2 btn btn-outline-success"
        >
          <i class="material-icons nav__icon">search</i>
        </button>
      </form>
    </div>
    <!-- end here -->
    <!--carosel -->
    <div
      id="carouselExampleIndicators"
      class="carousel slide"
      style="height: 300px"
      data-ride="carousel"
    >
      <ol class="carousel-indicators">
        <li
          data-target="#carouselExampleIndicators"
          data-slide-to="0"
          class="active"
        ></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        {% for i in menu %}
        <div
          class="
            carousel-item
            {%
            if
            forloop.counter
            ==
            1
            %}active{%
            else
            %}item{%
            endif
            %}
          "
        >
          <img
            class="d-block w-100"
            style="height: 300px !important"
            src="{{ i.Dish_image.url }}"
            alt="First slide"
          />
          <div class="carousel-caption">
            <h5 class="text-dark">{{ i.Dish_Name }}</h5>
            <p class="text-dark">
              <span class="" style="color: #abe63a">₹</span>{{ i.Price }}
            </p>
          </div>
        </div>
        {% endfor %}
      </div>
      <a
        class="carousel-control-prev"
        href="#carouselExampleIndicators"
        role="button"
        data-slide="prev"
      >
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a
        class="carousel-control-next"
        href="#carouselExampleIndicators"
        role="button"
        data-slide="next"
      >
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <br />
    <!-- end here -->
    {% if messages and table.rest_id == user.id %} {% for message in messages %}
    {% if message.tags == 'error' %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      {{ message }}
      <button
        type="button"
        class="close"
        data-dismiss="alert"
        aria-label="Close"
      >
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %}

    <div class="tabbale">
      <ul class="nav nav-tabs" id="myTab" role="tablist">
        {% for i in cat %}
        <li class="nav-item" role="presentation">
          <a
            class="nav-link {% if forloop.counter == 1 %}active{% endif %}"
            id="cat{{ i.id }}-tab"
            data-toggle="tab"
            href="#cat{{ i.id }}"
            role="tab"
            aria-controls="cat{{ i.id }}"
            aria-selected="{% if forloop.counter == 1 %}true{% endif %}"
          >
            {{ i.Category_Name }}</a
          >
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="tab-content" id="myTabContent">
      {% for j in cat %}
      <div
        class="
          tab-pane
          fade
          {%
          if
          forloop.counter
          ==
          1
          %}show
          active{%
          endif
          %}
        "
        id="cat{{ j.id }}"
        role="tabpanel"
        aria-labelledby="cat{{ j.id }}-tab"
      >
        {% for i in menu %} {% if j.Category_Name == i.category.Category_Name %}
        <div class="con">
          <div class="w3-panel w3-card-4">
            <div class="row">
              <div class="col-lg-3">
                <div class="horizontal-card">
                  <img src="{{ i.Dish_image.url }}" />
                  <div class="horizontal-card-body">
                    <h4 class="card-title">{{ i.Dish_Name }}</h4>
                    <span class="card-text" style="font-size: 12px"
                      >{{ i.Dish_Description }}</span
                    >
                    <p class="text-dark mt-2">
                      <b>
                        <span class="" style="color: #abe63a">₹</span>{{ i.Price
                        }}</b
                      >
                    </p>
                  </div>
                  <div class="horizontal-card-footer">
                    <a
                      class="minus"
                      href="{% url 'restaurant:remove_single' i.id table.id %}"
                    >
                      -
                    </a>
                    <a class="card-text status p-1"
                      >0 {% for j in cart %} {% if j.product.id == i.id %} {{
                      j.quantity }} {% endif %} {% endfor %}
                    </a>

                    <a
                      class="plus"
                      href="{% url 'restaurant:add_to_cart' i.id table.id %}"
                    >
                      +
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %} {% endfor %}
      </div>
      {% endfor %}
    </div>
    <br /><br /><br />
    <!-- fixed bottom -->
    <div class="foot">
      <nav class="nav">
        <a
          href="{% url 'restaurant:menu' table.rest.id table.table_no %}"
          class="nav__link"
        >
          <i class="material-icons nav__icon">dashboard</i>
          <span class="nav__text">MENU</span>
        </a>
        <a
          href="{% url 'restaurant:order_summary' table.rest.id table.table_no %}"
          class="nav__link nav__link--active"
        >
          <i class="material-icons nav__icon">person</i>
          <span class="nav__text">MY ORDERS</span>
        </a>
        <a href="#" data-catid="{{ table.id }}" class="nav__link c_wait">
          <i class="material-icons nav__icon">devices</i>
          <span class="nav__text">CALL A WAITER</span>
        </a>
      </nav>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
      <script type="text/javascript">
        $(".c_wait").click(function () {
          var catid;
          catid = $(this).attr("data-catid");
          $.ajax({
            type: "GET",
            url: "{% url 'restaurant:call_waiter' table.id %}",
            data: {},
            success: function (data) {},
          });
        });
      </script>
    </div>

    <!-- End Here -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </body>
</html>

templates/customer copy/order_sumery.html
<!doctype html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'menu_page/w3.css' %}">
    <link rel="stylesheet" href="{% static 'menu_page/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'menu_page/font-awesome.min.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'my_css/menu.css' %}">

    <title>Scan N Order</title>
</head>
<body style="margin-left: 18px; margin-right: 10px;">
<!-- navigation Start Here -->
<div class="topnav" style="background-color: #ABE63A;" id="myTopnav">
  <a href="#home" class="text-white">{{ table.rest.restaurant_name|capfirst }}</a>

</div>
<!-- end here -->

{% if orders %}
{% for i in orders.item.all %}
      <div class="con">
        <div class="w3-panel w3-card-4">

          <div class="row">
            <div class="col-lg-3">
              <div class="horizontal-card">

                <img src="{{ i.product.Dish_image.url }}" />
                <div class="horizontal-card-body">

                  <h4 class="card-title" >{{ i.product.Dish_Name }}</h4>
                  <span class="card-text" style="font-size: 12px;">{{ i.product.Dish_Description }}</span>
                    <p class="text-dark mt-2"><b> <span class="" style="color: #ABE63A">₹</span> {{ i.product.Price }}</b></p>
                    <p class="text-dark "><b> <span class="" style="color: #ABE63A">₹</span>{{ i.product.Price }} * {{ i.quantity }} = <span class="" style="color: #ABE63A">₹</span> {{ i.get_total_item_price }}</b></p>
                    <form action="{% url 'restaurant:com' i.id %}" method="get" id="add{{ i.id }}">

                    <input type="text" class="ml-1 col-8" name="com{{ i.id }}" placeholder="Add Comment">
                        <button type="submit" class="btn btn-light p-1" style="background-color: #ABE63A" form="add{{ i.id }}">Note</button>
                    </form>
                </div>
                <div class="horizontal-card-footer">
                  <a class="minus" href="{% url 'restaurant:remove_single' i.product.id table.id %}" > - </a>
                  <a class="card-text status p-1" >
                      0 {{ i.quantity }}
                  </a>

                   <a class="plus" href="{% url 'restaurant:add_to_cart' i.product.id table.id %}" > + </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {% endfor %}

      <div class="text-right footer p-2">
          Sub Total: <span class="" style="color: #ABE63A">₹</span>{{ orders.get_total }}<br>
            SGST {{ orders.table_no.rest.SGST }}%: {{ orders.sgst_price }}<br>
            CGST {{ orders.table_no.rest.CGST }}%: {{ orders.cgst_price }}<br>
          <hr>
            Total: {{ orders.sc_total }}
          <hr>
            Discount {{ orders.table_no.rest.discount }}
            <hr>
            Grand Total: <span class="" style="color: #ABE63A">₹</span>{{ orders.gst_total }}<br>
          <a href="{% url 'restaurant:place_order' table.rest.id table.table_no %}"><button   class="btn btn-outline-success col-12" style="background-color: white; color: #ABE63A; font-size: large" ><b>Place Order</b></button></a>

     </div>
{% endif %}
<br><br><br>
<!-- fixed bottom -->
<div class="foot">
<nav class="nav">
  <a href="{% url 'restaurant:menu' table.rest.id table.table_no %}" class="nav__link">
    <i class="material-icons nav__icon">dashboard</i>
    <span class="nav__text">MENU</span>
  </a>
  <a href="{% url 'restaurant:order_summary' table.rest.id table.table_no %}" class="nav__link nav__link--active">
    <i class="material-icons nav__icon">person</i>
    <span class="nav__text">MY ORDERS</span>
  </a>
  <a href="{% url 'restaurant:call_waiter' table.id %}" class="nav__link">
    <i class="material-icons nav__icon">devices</i>
    <span class="nav__text">CALL A WAITER</span>
  </a>

</nav>
</div>
<!-- End Here -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

</body>
</html>

templates/customer copy/ordersummary.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title> Shoping Cart Design Using Bootstrap 4.0 </title>
	<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="{% static 'my_css/custom.css' %}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

</head>
<body class="">
	<div class="container main-section">
		<div class="row">
         <center>

			<div class="col-lg-8 pl-3 pt-3">
				<table class="table table-hover border bg-white">
				    <thead>
				      	<tr>
					        <th>Product Image</th>
                            <th>Product Name</th>
					        <th>Price</th>
					        <th style="width:10%;">Quantity</th>
					        <th>Subtotal</th>
					        <th>Action</th>
				      	</tr>
				    </thead>
				    <tbody>
				      	{% for i in orders.item.all %}
				      	<tr>
					        <td>

									<div class=" Product-img">
										<img src="{{ i.product.Dish_image.url }}" alt="..." class="img-responsive"/>
									</div>


					        </td>
                            <td>
                                <div class="">
                                            <h4 class="nomargin">{{ i.product.Dish_Name }}</h4>
                                            <p>{{ i.product.Dish_Description }}</p>
                                </div>
                            </td>
					        <td> {{ i.product.Price }} </td>
					        <td data-th="Quantity">
								<input type="number" class="form-control text-center" value="{{ i.quantity }}">
							</td>
							<td> {{ i.get_total_item_price }}</td>
					        <td class="actions" data-th="" style="width:10%;">

								<button class="btn btn-danger btn-sm"><i class="fa fa-trash-o"></i></button>
							</td>
				      	</tr>
                    {% endfor %}
				    </tbody>
				    <tfoot>
						<tr>
							<td><a href="#" class="btn btn-warning text-white"><i class="fa fa-angle-left"></i> Continue Shopping</a></td>
							<td colspan="2" class="hidden-xs"></td>
							<td class="hidden-xs text-center" style="width:10%;"><strong>Discount:{{ orders.table_no.rest.discount }}<br>
                                Total : {{ orders.get_total }}</strong></td>
							<td><a href="#" class="btn btn-success btn-block">Checkout <i class="fa fa-angle-right"></i></a></td>
						</tr>
					</tfoot>
				</table>
			</div>
        </center>
		</div>

	</div>


<nav class="nav">
  <a href="{% url 'restaurant:menu' table.rest.id  table.table_no %}" class="nav__link">
    <i class="material-icons nav__icon">dashboard</i>
    <span class="nav__text">Menu</span>
  </a>
  <a href="#" class="nav__link nav__link--active">
    <i class="material-icons nav__icon">person</i>
    <span class="nav__text">My Orders</span>
  </a>
  <a href="#" class="nav__link">
    <i class="material-icons nav__icon">devices</i>
    <span class="nav__text">Call A Waiter</span>
  </a>

</nav>
</body>
</html>

templates/customer copy/place_s.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
successfully placed
</body>
</html>