reastaurant_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('  /', include('manager.urls')),
    path('rest_admin/', include('rest_admin.urls')),
    path('waiter/', include('waiter.urls')),
    path('kitchen/', include('kitchen.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('webpush/', include('webpush.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rest_admin/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'rest_admin'

urlpatterns = [

    path('qr/', views.qr, name='qr'),
    path('add_menu/', views.add_menu, name='add_menu'),
    path('add_employee/', views.add_employee, name='add_employee'),
    path('add_category/', views.add_categories, name='add_category'),
    path('cat_list/', views.category_list, name='cat_list'),
    path('menu_list/', views.menu_list, name='menu_list'),
    path('menu_state/<int:id>/', views.menu_avc, name='menu_state'),
    path('emp_list/', views.employee_list, name='emp_list'),
    path('edit_cat/<int:id>/', views.cat_form_edit, name='edit_cat'),
    path('delete_cat/<int:id>/', views.delete, name='delete_cat'),
    path('edit_emp/<int:id>/', views.emp_form_edit, name='edit_emp'),
    path('delete_emp/<int:id>/', views.emp_delete, name='delete_emp'),
    path('edit_menu/<int:id>/', views.menu_form_edit, name='edit_menu'),
    path('delete_menu/<int:id>/', views.menu_delete, name='delete_menu'),
    path('t_earn/', views.t_price, name='t_price'),

    path('orders/', views.orders, name='orders'),
    path('t_orders/', views.today_order, name='t_order'),
    path('orders_det/<int:id>/', views.order_details, name='order_det'),
    path('complete/<int:id>/', views.order_complete, name='order_complete'),
    path('pdf/<int:id>/', views.GeneratePdf.as_view(), name='pdf'),
    path('menu_state/<int:id>/', views.menu_avc, name='menu_state'),
    path('user_profile/', views.user_details, name='user_profile'),
    path('update_u/<int:id>/', views.update_details, name='update_u'),

    path('table_view/', views.table_view, name='table_view'),
    path('edit_table/<int:id>/', views.table_edit, name='edit_table'),
    path('delete_table/<int:id>/', views.table_delete, name='delete_table'),

    path('table_list/', views.table_list, name='table_list'),

    path('com_u/<int:id>/', views.com_edit, name='com_u'),

    path('add_manager/', views.add_manager, name='add_manager'),
    path('manager_list/', views.manager_list, name='manager_list'),
    path('manager_form_edit/<int:id>/',
         views.manager_form_edit, name='manager_form_edit'),
    path('manager_delete/<int:id>/', views.manager_delete, name='manager_delete'),

    path('add_expenses/', views.add_day_expenses, name='add_day_expenses'),
    path('manage_day_expenses/', views.manage_day_expenses, name='manage_day_expenses'),
    path('edit_expenses/<int:id>', views.edit_expenses, name='edit_expenses'),

    path('add_month_expenses/', views.add_month_expenses, name='add_month_expenses'),
    path('manage_month_expenses/', views.manage_month_expenses, name='manage_month_expenses'),
    path('edit_month_expenses/<int:id>', views.edit_month_expenses, name='edit_month_expenses'),

    path('balence_sheet/', views.balence_sheet, name='balence_sheet'),

    path('add_assests/', views.add_assests, name='add_assests'),
    path('manage_assests/', views.manage_assests, name='manage_assests'),
    path('edit_assests/<int:id>', views.edit_assests, name='edit_assests'),
    path('add_unit/', views.add_unit, name='add_unit'),
    path('unit_list/', views.unit_list, name='unit_list'),
    path('edit_unit/<int:id>', views.edit_unit, name='edit_unit'),
    path('delete_unit/<int:id>', views.delete_unit, name='delete_unit'),
    
    path('add_inventory/', views.add_inventory, name='add_inventory'),
    path('inventory_list/', views.inventory_list, name='inventory_list'),
    path('edit_inventory/<int:id>', views.edit_inventory, name='edit_inventory'),
    path('delete_inventory/<int:id>', views.delete_inventory, name='delete_inventory'),
    

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

waiter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'waiter'

urlpatterns = [
    path('', views.table_view, name='table_view'),
    path('manual_order/<int:id>/', views.manual_order, name='manual_order'),
    path('t_orders/', views.today_order, name='t_order'),
] + static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

rest_admin/views.py
from django.template.loader import get_template
from .utils import render_to_pdf  # created in step 4
from django.views.generic import View
from django.http import HttpResponse
import datetime
from django.contrib import messages
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, get_object_or_404, redirect
from django.urls import reverse
from .models import *
from .forms import *
from accounts.forms import RestaurantForm
from accounts.models import User
from restaurant.models import *
from django.db.models import Count
from itertools import chain

# Create your views here.
def t_price(request):
    restro = User.objects.get(id=request.user.id)
    res = User.objects.get(id=request.user.id)
    order_list =  Order.objects.filter(table_no__rest=res.id, ordered=True, status="complete",
                  start_date__date__day=datetime.datetime.today().day,
                  start_date__date__month=datetime.datetime.today().month,
                  start_date__date__year=datetime.datetime.today().year)

    parcel_order_list = Parcel_Order.objects.filter(customer__rest=res.id, ordered=True, status="complete",
                  start_date__date__day=datetime.datetime.today().day,
                  start_date__date__month=datetime.datetime.today().month,
                  start_date__date__year=datetime.datetime.today().year)
                  
    order_list2 = Order.objects.filter(table_no__rest=res.id, ordered=True, status="complete",
                  start_date__date__month=datetime.datetime.today().month,
                  start_date__date__year=datetime.datetime.today().year)

    parcel_order_list2 = Parcel_Order.objects.filter(customer__rest=res.id, ordered=True, status="complete",
                  start_date__date__month=datetime.datetime.today().month,
                  start_date__date__year=datetime.datetime.today().year)

    total_emp = User.objects.filter(rest_id=request.user, is_employee=True)

    total_earn = Order.objects.filter(
        table_no__rest_id=res.id, ordered=True)

    parcel_total_earn = Parcel_Order.objects.filter(
        customer__rest_id=res.id, ordered=True)

    total_1 = 0
    total_2 = 0

    m_total_1 = 0
    m_total_2 = 0

    a_total_1 = 0
    a_total_2 = 0

    total = 0
    m_total = 0
    a_total = 0

    for i in order_list:
        total_1 += i.gst_total()

    for a in parcel_order_list:
        total_2 += a.gst_total()

    total = total_1 + total_2


    for j in order_list2:
        m_total_1 += j.gst_total()

    for b in parcel_order_list2:
        m_total_2 += b.gst_total()

    m_total = m_total_1 + m_total_2


    for k in total_earn:
        a_total_1 += k.gst_total()

    for c in parcel_total_earn:
        a_total_2 += c.gst_total()

    a_total = a_total_1 + a_total_2


    ### month bar chart ######
    month = [1,2,3,4,5,6,7,8,9,10,11,12]

    months_earn = []
    
    calc = 0

    for i in month:
        data_1 = Order.objects.filter(table_no__rest=res.id, ordered=True, status="complete", start_date__date__month=i, start_date__date__year=2021)
        data_2 = Parcel_Order.objects.filter(customer__rest=res.id, ordered=True, status="complete", start_date__date__month=i, start_date__date__year=2021)
        
        data = list(chain(data_1, data_2))

        if not data:
            months_earn.append(0)
        else:
            for j in data:     
                calc += j.gst_total()
            
            months_earn.append(calc)
            calc = 0

    ########## best seller bar chart ########

    best_data = OrderItem.objects.filter(table_no__rest=res.id, ordered=True, date__date__month=datetime.datetime.today().month,date__date__year=datetime.datetime.today().year)
    # best_data = Parcel_OrderItem.objects.filter(customer__rest=res.id, ordered=True, date__date__month=datetime.datetime.today().month,date__date__year=datetime.datetime.today().year)
    
    # best_data = chain(best_data_1, best_data_2)

    
    dish_count = []

    dish_name = []

    top_sell = best_data.values_list('product_id').annotate(product_count=Count('product_id')).order_by('-product_count')[:10]
    
    for i in top_sell:
        dish_name.append(MenuTable.objects.get(id=i[0]).Dish_Name)
        dish_count.append(i[1])

    ########## expenses ############
    year = datetime.datetime.today().year
    month = datetime.datetime.today().month
    day_earn_1 = Order.objects.filter(table_no__rest_id=res.id, ordered=True, start_date__year=year,
                                        start_date__month=month)
    day_earn_2 = Parcel_Order.objects.filter(customer__rest_id=res.id, ordered=True, start_date__year=year,
                                        start_date__month=month)

    day_earn = list(chain(day_earn_1, day_earn_2))         

    day_total = 0
    
    for i in day_earn:
        day_total += i.gst_total()
                        
    day_expense = Expenses.objects.filter(res_id=res.id, Date__year=year, Date__month=month)

    expense_total = 0
    for i in day_expense:
        expense_total += i.Day_Expense + i.Others


    per_month_expense = PerMonthExpenses.objects.filter(res_id=res.id, Date__date__year=year, Date__date__month=month)

    month_expense = 0 

    for i in per_month_expense:

        month_expense = i.Rent + i.Light_Bill + i.Others


    salary = User.objects.filter(rest_id=res.id, is_employee=True)

    sal = 0

    for i in salary:
        sal += i.salary
    
    assests_total = Assests.objects.filter(res_id=res.id, Date__date__year=year, Date__date__month=month)
    
    a_total = 0

    for i in assests_total:
        a_total += i.Furnishing + i.Kitchen_equipements + i.Others
    

    final_earn = a_total + day_total

    final_Expense = sal + month_expense + expense_total
    

    return render(request, 'rest_admin/t_earn.html', {'total': total, 'm_total': m_total, 'total_emp': total_emp,
                                                      'a_total': a_total, 'restro': restro, 'months_earn':months_earn,'dish_name':dish_name,'dish_count':dish_count, 'final_earn':final_earn, 'final_Expense':final_Expense})


def qr(request):
    restro = User.objects.get(id=request.user.id)
    res = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = QrForm(request.POST, request.FILES)

        if form.is_valid():

            form_r = form.save(commit=False)
            form_r.rest = res
            form_r.status = 'available'
            form_r.save()
            return redirect('rest_admin:table_list')
        else:
            print(form.errors)
    else:
        form = QrForm()
    return render(request, 'rest_admin/index.html', {
        'form': form,
        'restro': restro
    })


def add_menu(request):
    restro = User.objects.get(id=request.user.id)
    res = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = AddMenuForm(res.id, request.POST, request.FILES)

        if form.is_valid():

            form_r = form.save(commit=False)
            form_r.res = res
            form_r.status = 'available'
            form_r.save()
            return redirect('rest_admin:menu_list')
        else:
            print(form.errors)
    else:
        form = AddMenuForm(res.id)
    return render(request, 'rest_admin/add_menu.html', {
        'form': form,
        'restro': restro
    })


def add_employee(request):
    restro = User.objects.get(id=request.user.id)
    res = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = EmployeeForm(request.POST, request.FILES)

        if form.is_valid():

            form_r = form.save(commit=False)
            form_r.set_password(form_r.password)
            form_r.rest = res
            form_r.is_employee = True
            form_r.save()
            return redirect('rest_admin:emp_list')
        else:
            print(form.errors)
    else:
        form = EmployeeForm()

    return render(request, 'rest_admin/add_employee.html', {
        'form': form,
        'restro': restro
    })


def add_categories(request):
    restro = User.objects.get(id=request.user.id)
    res = User.objects.get(id=request.user.id)
    if request.method == 'POST':
        form = AddCategoryForm(request.POST, request.FILES)

        if form.is_valid():

            form_r = form.save(commit=False)
            form_r.rest = res
            form_r.save()
            return redirect('rest_admin:cat_list')
        else:
            print(form.errors)
    else:
        form = AddCategoryForm()
    return render(request, 'rest_admin/add_category.html', {
        'form': form,
        'restro': restro
    })


def category_list(request):
    restro = User.objects.get(id=request.user.id)
    res = User.objects.get(id=request.user.id)
    cat_list = Categories.objects.filter(rest_id=res)
    return render(request, 'rest_admin/cat_list.html', {
        'cat_list': cat_list,
        'restro': restro
    })


def menu_list(request):
    restro = User.objects.get(id=request.user.id)
    res = User.objects.get(id=request.user.id)
    menu_lists = MenuTable.objects.filter(res_id=res)
    return render(request, 'rest_admin/menu_list.html', {
        'menu_lists': menu_lists,
        'restro': restro
    })


def employee_list(request):
    restro = User.objects.get(id=request.user.id)
    res = User.objects.get(id=request.user.id)
    emp_lists = User.objects.filter(is_employee=True, rest_id=res.id)
    print(emp_lists)
    return render(request, 'rest_admin/emp_list.html', {
        'emp_lists': emp_lists,
        'restro': restro
    })


def cat_form_edit(request, id):
    restro = User.objects.get(id=request.user.id)
    instance = get_object_or_404(Categories, id=id)

    form = AddCategoryForm(request.POST or None, instance=instance)

    if form.is_valid():
        form.save()
        return redirect('rest_admin:cat_list')
    return render(request, 'rest_admin/cat_edit.html', {
        'form': form,

templates/rest_admin/cat_list.html
<!DOCTYPE html>
{% extends 'res_base.html' %} 
{% load static %} 
  {% block head %}
    <link href="{% static 'my_css/qr.css' %}" rel="stylesheet" />
  {% endblock %} 

{% block body %} 
  {% if messages and order_det.table_no.rest_id == user.user_id %}
    {% for message in messages %} 
      {% if message.tags == 'warning' %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endif %} 
    {% endfor %} 
  {% endif %}
  
  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Categories</h4>
        <p class="card-category">Manage Categories From Here</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary">
              <tr>
                <th>ID</th>
                <th>Category Image</th>
                <th>Name</th>
                <th>Description</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>
              {% for i in cat_list %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                  <img
                    src="{{ i.Category_Image.url }}"
                    width="80px"
                    height="50px"
                  />
                </td>
                <td>{{ i.Category_Name }}</td>
                <td>{{ i.Description }}</td>
                <td class="td-actions">
                  <a
                    href="{% url 'rest_admin:edit_cat' i.id %}"
                    class="btn btn-success"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">edit</i>
                    <div class="ripple-container"></div
                  ></a>

                  <a
                    href="{% url 'rest_admin:delete_cat' i.id %}"
                    class="btn btn-danger"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">close</i>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/rest_admin/emp_list.html
<!DOCTYPE html>
{% extends 'res_base.html' %} 
{% load static %} 
  {% block head %}
    <link href="{% static 'my_css/qr.css' %}" rel="stylesheet" />
  {% endblock %} 

{% block body %} 
  {% if messages and order_det.table_no.rest_id == user.user_id %}
    {% for message in messages %} 
      {% if message.tags == 'warning' %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endif %} 
    {% endfor %} 
  {% endif %}
  
  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Employee</h4>
        <p class="card-category">Manage Employees From Here</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary">
              <tr>
                <th>ID</th>
                <th>Profile Picture</th>
                <th>Name</th>
                <th>Mobile Number</th>
                <th>Address</th>
                <th>State</th>

                <th>Category</th>
                <th>Salary</th>
                <th>Adhaar Card</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for i in emp_lists %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                  {% if i.profile_photo %}
                  <img
                    src="{{ i.profile_photo.url }}"
                    width="80px"
                    height="50px"
                  />
                  {% endif %}
                </td>
                <td>{{ i.first_name }} {{ i.last_name }}</td>
                <td>{{ i.mobile_no }}</td>
                <td>{{ i.address }}</td>
                <td>{{ i.country }}, {{ i.state }}</td>

                <td>{{ i.Category }}</td>
                <td>{{ i.salary }}</td>
                <td>
                  <a class="btn btn-primary" href="{{ i.Adhaar_Card.url }}"
                    >Download</a
                  >
                </td>

                <td class="td-actions">
                  <a
                    href="{% url 'rest_admin:edit_emp' i.id  %}"
                    class="btn btn-success"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">edit</i>
                    <div class="ripple-container"></div
                  ></a>

                  <a
                    href="{% url 'rest_admin:delete_emp' i.id %}"
                    class="btn btn-danger"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">close</i>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/rest_admin/inventory_list.html
<!DOCTYPE html>
{% extends 'res_base.html' %} 
{% load static %} 
  {% block head %}
    <link href="{% static 'my_css/qr.css' %}" rel="stylesheet" />
  {% endblock %} 
  
{% block body %} 
  {% if messages and order_det.table_no.rest_id == user.user_id %}
    {% for message in messages %} 
      {% if message.tags == 'warning' %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endif %} 
    {% endfor %} 
  {% endif %}

  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Inventory</h4>
        <p class="card-category">Manage Inventory From Here</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary">
              <tr>
                <th>ID</th>
                <th>Item Name</th>
                <th>Quantity</th>
                <th>Unit</th>
                <th>Price</th>
                <th>Date</th>

                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for i in data %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ i.Item_Name }}</td>
                <td>{{ i.Item_Amount }}</td>
                <td>{{ i.Unit }}</td>
                <td>Rs.{{ i.Item_Price }}/-</td>
                <td>{{ i.Date.date }}</td>

                <td class="td-actions">
                  <a
                    href="{% url 'rest_admin:edit_inventory' i.id %}"
                    class="btn btn-success"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">edit</i>
                    <div class="ripple-container"></div
                  ></a>

                  <a
                    href="{% url 'rest_admin:delete_inventory' i.id %}"
                    class="btn btn-danger"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">close</i>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/rest_admin/menu_list.html
<!DOCTYPE html>
{% extends 'res_base.html' %} 
{% load static %} 
  {% block head %}
    <link href="{% static 'my_css/qr.css' %}" rel="stylesheet" />
  {% endblock %} 
  
{% block body %} 
  {% if messages and order_det.table_no.rest_id == user.user_id %}
    {% for message in messages %} 
      {% if message.tags == 'warning' %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endif %} 
    {% endfor %} 
  {% endif %}

  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Menu</h4>
        <p class="card-category">Manage Menu From Here</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary">
              <tr>
                <th>ID</th>
                <th>Dish Image</th>
                <th>Dish Name</th>
                <th>Description</th>
                <th>Category</th>
                <th>Price</th>
                <th>Quantity</th>

                <th>Status</th>
                <th>Change Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for i in menu_lists %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                  <img src="{{ i.Dish_image.url }}" width="80px" height="50px" />
                </td>
                <td>{{ i.Dish_Name }}</td>
                <td>{{ i.Dish_Description }}</td>
                <td>{{ i.category }}</td>
                <td>{{ i.Price }}</td>

                <td>{{ i.pices }}</td>
                <td>{{ i.status|capfirst }}</td>
                <td>
                  {% if i.status == 'available' %}
                  <a
                    href="{% url 'rest_admin:menu_state' i.id %}"
                    class="btn btn-danger"
                    data-original-title=""
                    title=""
                  >
                    NA
                  </a>
                  {% else %}
                  <a
                    href="{% url 'rest_admin:menu_state' i.id %}"
                    class="btn btn-success"
                    data-original-title=""
                    title=""
                  >
                    A
                  </a>
                  {% endif %}
                </td>

                <td class="td-actions">
                  <a
                    href="{% url 'rest_admin:edit_menu' i.id %}"
                    class="btn btn-success"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">edit</i>
                    <div class="ripple-container"></div
                  ></a>

                  <a
                    href="{% url 'rest_admin:delete_menu' i.id %}"
                    class="btn btn-danger"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">close</i>
                  </a>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/rest_admin/today_order.html
<!DOCTYPE html>
{% extends 'res_base.html' %} 
{% load static %} 
  {% block head %}
    <link href="{% static 'my_css/qr.css' %}" rel="stylesheet" />
  {% endblock %} 
{% block body %} 
  {% if messages and order_det.table_no.rest_id == user.user_id %}
    {% for message in messages %} 
      {% if message.tags == 'warning' %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endif %} 
    {% endfor %} 
  {% endif %}

  <div class="col-md-12">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Today's Order</h4>
        <p class="card-category">Manage Order From Here</p>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table">
            <thead class="text-primary">
              <tr>
                <th>ID</th>
                <th>Order ID</th>
                <th>Table No</th>
                <th>Dish Name</th>

                <th>Quantity</th>
                <th>Comment</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {% for i in order_list %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ i.id }}</td>
                <td>{{ i.table_no.table_no }}</td>
                <td>
                  {% for j in i.item.all %} {{ j.product.Dish_Name }}<br />
                  {% endfor %}
                </td>

                <td>
                  {% for j in i.item.all %} {{ j.quantity }}<br />
                  {% endfor %}
                </td>
                <td class="td-actions">
                  {% for j in i.item.all %} {{ j.comment }}
                  <a
                    href="{% url 'rest_admin:com_u' j.id %}"
                    class="btn btn-success"
                    data-original-title=""
                    title=""
                  >
                    <i class="material-icons">edit</i> </a
                  ><br /><br />
                  {% endfor %}
                </td>
                <td>
                  {% for j in i.item.all %} {{ j.status }}<br />
                  {% endfor %}
                </td>

                <td>
                  <a class="btn btn-primary" href="{% url 'rest_admin:pdf' i.id%}"
                    >PAYMENT</a
                  >
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

  <div class="col-md-12">
  <div class="card">
    <div class="card-header card-header-primary">
      <h4 class="card-title ">Today's Order(Parcel)</h4>
      <p class="card-category"> Manage Parcel Order From Here</p>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table">
          <thead class=" text-primary">
            <tr>
              <th>
                ID
              </th>
              <th>
                Order ID
              </th>
              <th>
                Customer Name
              </th>
              <th>
                Dish Name
              </th>

              <th>
                Quantity
              </th>
              <th>
                Comment
              </th>
              <th>
                Status
              </th>
              <th>
                Actions
              </th>


            </tr>
          </thead>
          <tbody>
            {% for i in parcel_order_list %}
            <tr>
              <td>
                {{ forloop.counter }}
              </td>
              <td>
                {{ i.id }}
              </td>
              <td>
                {{ i.customer.name }}
              </td>
              <td>
                {% for j in i.item.all %}
                {{ j.product.Dish_Name }}<br>
                {% endfor %}
              </td>

              <td>
                {% for j in i.item.all %}
                {{ j.quantity }}<br>
                {% endfor %}
              </td>
              <td class="td-actions">
                {% for j in i.item.all %}
                {{ j.comment }}
                <a href="{% url 'rest_admin:com_u' j.id %}" class="btn btn-success" data-original-title="" title="">
                  <i class="material-icons">edit</i>
                </a><br><br>
                {% endfor %}
              </td>
              <td>
                {% for j in i.item.all %}
                {{ j.status }}<br>
                {% endfor %}
              </td>

              <td>
                <a class="btn btn-primary" href="{% url 'rest_admin:pdf' i.id%}">PAYMENT</a>

              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endblock %}